version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
    env_file:
      - ./aws.env
    volumes:
      - ./:/go/src/github.com/silinternational/slack-bot-sms-reminder
    working_dir: /go/src/github.com/silinternational/slack-bot-sms-reminder
    command: ["bash"]

  dynamo:
    image: cnadiminti/dynamodb-local
    command: "-sharedDb -inMemory"
    hostname: dynamo
    ports:
      - "8000:8000"
    environment:
      reschedule: on-node-failure

  init-dynamo:
    image: garland/aws-cli-docker
    command: "/init-dynamodb.sh"
    volumes:
      - ./codeship/init-dynamodb.sh:/init-dynamodb.sh
    depends_on:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DYNAMODB_ENDPOINT=http://dynamo:8000

  test:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - init-dynamo
    environment:
      AWS_ACCESS_KEY_ID: 0
      AWS_SECRET_ACCESS_KEY: 0
      AWS_DEFAULT_REGION: us-east-1
      AWS_DYNAMODB_ENDPOINT: http://dynamo:8000
      SLACK_APP_ID: abc123
      SLACK_CLIENT_ID: abc123
      SLACK_CLIENT_SECRET: abc123
      SLACK_SIGNING_SECRET: abc123
      SLACK_VERIFICATION_TOKEN: abc123
    volumes:
      - ./:/go/src/github.com/silinternational/slack-bot-sms-reminder
    working_dir: /go/src/github.com/silinternational/slack-bot-sms-reminder
    command: ["bash"]